package cn.edu.upc.hyz.model;

import java.util.Date;

public class ProjectApply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.id
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.project_name
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.applicant
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    private String applicant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.place
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    private Integer place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.create_time
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.end_time
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.remark
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.del_flag
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.id
     *
     * @return the value of project_apply.id
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.id
     *
     * @param id the value for project_apply.id
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.project_name
     *
     * @return the value of project_apply.project_name
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.project_name
     *
     * @param projectName the value for project_apply.project_name
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.applicant
     *
     * @return the value of project_apply.applicant
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.applicant
     *
     * @param applicant the value for project_apply.applicant
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant == null ? null : applicant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.place
     *
     * @return the value of project_apply.place
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public Integer getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.place
     *
     * @param place the value for project_apply.place
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public void setPlace(Integer place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.create_time
     *
     * @return the value of project_apply.create_time
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.create_time
     *
     * @param createTime the value for project_apply.create_time
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.end_time
     *
     * @return the value of project_apply.end_time
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.end_time
     *
     * @param endTime the value for project_apply.end_time
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.remark
     *
     * @return the value of project_apply.remark
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.remark
     *
     * @param remark the value for project_apply.remark
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.del_flag
     *
     * @return the value of project_apply.del_flag
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.del_flag
     *
     * @param delFlag the value for project_apply.del_flag
     *
     * @mbg.generated Wed Jun 10 10:13:53 CST 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}