package cn.edu.upc.hyz.dao;

import cn.edu.upc.hyz.model.Area;


import java.util.List;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Fri Mar 13 09:02:16 CST 2020
     */
    List<Area> select();

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Fri Mar 13 09:02:16 CST 2020
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Fri Mar 13 09:02:16 CST 2020
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Fri Mar 13 09:02:16 CST 2020
     */
    Area selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Fri Mar 13 09:02:16 CST 2020
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area
     *
     * @mbg.generated Fri Mar 13 09:02:16 CST 2020
     */
    int updateByPrimaryKey(Area record);
}