package cn.edu.upc.hyz.dao;

import cn.edu.upc.hyz.model.PrivilegeManage;

import java.util.List;

public interface PrivilegeManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege_manage
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege_manage
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    int insert(PrivilegeManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege_manage
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    int insertSelective(PrivilegeManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege_manage
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    PrivilegeManage selectByPrimaryKey(long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege_manage
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    int updateByPrimaryKeySelective(PrivilegeManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege_manage
     *
     * @mbg.generated Fri Mar 13 14:58:24 CST 2020
     */
    int updateByPrimaryKey(PrivilegeManage record);


    List<PrivilegeManage> selectAll();

    int deleteById(long id);
}