package cn.edu.upc.hyz.dao;

import cn.edu.upc.hyz.model.ProjectApply;

public interface ProjectApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Wed Jun 10 13:48:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Wed Jun 10 13:48:27 CST 2020
     */
    int insert(ProjectApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Wed Jun 10 13:48:27 CST 2020
     */
    int insertSelective(ProjectApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Wed Jun 10 13:48:27 CST 2020
     */
    ProjectApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Wed Jun 10 13:48:27 CST 2020
     */
    int updateByPrimaryKeySelective(ProjectApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Wed Jun 10 13:48:27 CST 2020
     */
    int updateByPrimaryKey(ProjectApply record);
}